Models/Tablero.cs
using tl2_tp10_2023_ezemrtz.ViewModels;

namespace tl2_tp10_2023_ezemrtz;

public class Tablero{
    private int id;
    private int idUsuarioPropietario;
    private string nombre;
    private string? descripcion;

    public int Id { get => id; set => id = value; }
    public int IdUsuarioPropietario { get => idUsuarioPropietario; set => idUsuarioPropietario = value; }
    public string Nombre { get => nombre; set => nombre = value; }
    public string? Descripcion { get => descripcion; set => descripcion = value; }

    public Tablero(){
        this.nombre = string.Empty;
    }
    public Tablero(CrearTableroViewModel tablero){
        this.idUsuarioPropietario = tablero.IdUsuarioPropietario;
        this.nombre = tablero.Nombre;
        this.descripcion = tablero.Descripcion;
    }
    public Tablero(ModificarTableroViewModel tablero){
        this.id = tablero.Id;
        this.idUsuarioPropietario = tablero.IdUsuarioPropietario;
        this.nombre = tablero.Nombre;
        this.descripcion = tablero.Descripcion;
    }   
}

Controllers/TableroController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using tl2_tp10_2023_ezemrtz.Models;
using tl2_tp10_2023_ezemrtz.Repositorios;
using tl2_tp10_2023_ezemrtz.ViewModels;

namespace tl2_tp10_2023_ezemrtz.Controllers;


public class TableroController : Controller
{
    private readonly ITableroRepository _tableroRepository;
    private readonly ITareaRepository _tareaRepository;
    private readonly IUsuarioRepository _usuarioRepository;
    private readonly ILogger<TableroController> _logger;

    public TableroController(ILogger<TableroController> logger, ITableroRepository tableroRepository, ITareaRepository tareaRepository, IUsuarioRepository usuarioRepository)
    {
        _logger = logger;
        _tableroRepository = tableroRepository;
        _tareaRepository = tareaRepository;
        _usuarioRepository = usuarioRepository;
    }

    public IActionResult Index(){
        try
        {
            if(!logueado()) return RedirectToRoute(new {controller = "Login", action = "Index"});
            if(esAdmin()){
                var tableros = _tableroRepository.GetAll();
                var usuarios = _usuarioRepository.GetAll();
                var idUserLogueado = Convert.ToInt32(HttpContext.Session.GetInt32("id"));

                return View(new ListarTablerosViewModel(_tableroRepository.GetAll(),_tableroRepository.GetByUser(idUserLogueado), _tableroRepository.GetByAssignedTask(idUserLogueado), _usuarioRepository.GetAll(), idUserLogueado));
            }else{
                var idUserLogueado = Convert.ToInt32(HttpContext.Session.GetInt32("id"));
                return View(new ListarTablerosViewModel(_tableroRepository.GetByUser(idUserLogueado), _tableroRepository.GetByAssignedTask(idUserLogueado), _usuarioRepository.GetAll(), idUserLogueado));
            }
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return RedirectToAction("Error");
        }
    }

    [HttpGet]
    public IActionResult CreateTablero(){
        try
        {
            if(!logueado()) return RedirectToRoute(new {controller = "Login", action = "Index"});
            return View(new CrearTableroViewModel{IdUsuarioPropietario = Convert.ToInt32(HttpContext.Session.GetInt32("id"))});
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return RedirectToAction("Error");
        }
    }

    [HttpPost]
    public IActionResult CreateTablero(CrearTableroViewModel tablero){
        try
        {
            if(!logueado()) return RedirectToRoute(new {controller = "Login", action = "Index"});
            if(!ModelState.IsValid) return RedirectToAction("Index");

            _tableroRepository.Create(new Tablero(tablero));
            return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return RedirectToAction("Error");
        }
    }

    [HttpGet]
    public IActionResult UpdateTablero(int id){
        try
        {
            if(!logueado()) return RedirectToRoute(new {controller = "Login", action = "Index"});
            var tablero = _tableroRepository.Get(id);
            if(tablero == null || (!esAdmin() && tablero.IdUsuarioPropietario != Convert.ToInt32(HttpContext.Session.GetInt32("id")))) return RedirectToAction("Error");
            return View(new ModificarTableroViewModel(_tableroRepository.Get(id)));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return RedirectToAction("Error");
        }
    }
    [HttpPost]
    public IActionResult UpdateTablero(ModificarTableroViewModel tablero){
        try
        {
            if(!logueado()) return RedirectToRoute(new {controller = "Login", action = "Index"});
            if(!ModelState.IsValid) return RedirectToAction("Index");
            _tableroRepository.Update(tablero.Id, new Tablero(tablero));
            return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return RedirectToAction("Error");
        }
    }

    public IActionResult DeleteTablero(int id){
        try
        {
            if(!logueado()) return RedirectToRoute(new {controller = "Login", action = "Index"});
            if(!esAdmin()){
                var tablero = _tableroRepository.Get(id);
                if(Convert.ToInt32(HttpContext.Session.GetInt32("id")) != tablero.IdUsuarioPropietario) return RedirectToAction("Error");
            }
            var tareas = _tareaRepository.GetByTablero(id);
            foreach (var tarea in tareas)
            {
                _tareaRepository.Remove(tarea.Id);
            }
            _tableroRepository.Remove(id);
            return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return RedirectToAction("Error");
        }
    }

    public IActionResult Error(){
        return View(new ErrorViewModel());
    }

    private bool logueado(){
        return HttpContext.Session.Keys.Any();
    }

    private bool esAdmin(){
        return HttpContext.Session.Keys.Any() && HttpContext.Session.GetString("rol") == NivelAcceso.administrador.ToString();
    }
}

Controllers/TareaController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using tl2_tp10_2023_ezemrtz.Models;
using tl2_tp10_2023_ezemrtz.Repositorios;
using tl2_tp10_2023_ezemrtz.ViewModels;


namespace tl2_tp10_2023_ezemrtz.Controllers;


public class TareaController : Controller
{
    private readonly ITareaRepository _tareaRepository;
    private readonly ITableroRepository _tableroRepository;
    private readonly IUsuarioRepository _usuarioRepository;
    private readonly ILogger<TareaController> _logger;

    public TareaController(ILogger<TareaController> logger, ITableroRepository tableroRepository, ITareaRepository tareaRepository, IUsuarioRepository usuarioRepository)
    {
        _logger = logger;
        _tareaRepository = tareaRepository;
        _tableroRepository = tableroRepository;
        _usuarioRepository = usuarioRepository;
    }

    public IActionResult Index(int id){
        try
        {
            if(!logueado()) return RedirectToRoute(new {controller = "Login", action = "Index"});
            if(!esAdmin()){
                var idUser = Convert.ToInt32(HttpContext.Session.GetInt32("id"));
                var tableros = _tableroRepository.GetByUser(idUser);
                var tareas = _tareaRepository.GetByTablero(id);
                if(tableros.Any(t => t.Id == id) || tareas.Any(t => t.IdUsuarioAsignado == idUser)){
                    return View(new ListarTareasViewModel(tareas, _tableroRepository.GetAll(), _usuarioRepository.GetAll()));
                }
            }else{

                return View(new ListarTareasViewModel(_tareaRepository.GetByTablero(id), _tableroRepository.GetAll(), _usuarioRepository.GetAll()));
            }
            return RedirectToRoute(new {controller = "Tablero", action = "Index"});
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return RedirectToAction("Error");
        }
    }
    public IActionResult GetTareas(){
        try
        {
            if(!logueado()) return RedirectToRoute(new {controller = "Login", action = "Index"});
            if(!esAdmin()){
                var idUser = Convert.ToInt32(HttpContext.Session.GetInt32("id"));
                var tareasAsignadas = _tareaRepository.GetByUser(idUser);
                return View(new ListarTareasViewModel(tareasAsignadas, _tableroRepository.GetAll(), _usuarioRepository.GetAll()));
            }else{
                return View(new ListarTareasViewModel(_tareaRepository.GetAll(), _tableroRepository.GetAll(), _usuarioRepository.GetAll()));
            }
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return RedirectToAction("Error");
        }
    }

    [HttpGet]
    public IActionResult CreateTarea(int id){
        try
        {
            if(!logueado()) return RedirectToRoute(new {controller = "Login", action = "Index"});
            var tablero = _tableroRepository.Get(id);
            if(tablero == null || (!esAdmin() && tablero.IdUsuarioPropietario != Convert.ToInt32(HttpContext.Session.GetInt32("id")))) return RedirectToAction("Error");
            var tarea = new CrearTareaViewModel{
                IdTablero = id,
                Usuarios = _usuarioRepository.GetAll()
            };
            return View(tarea);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return RedirectToAction("Error");
        }
    }

    [HttpPost]
    public IActionResult CreateTarea(CrearTareaViewModel tarea){
        try
        {
            if(!logueado()) return RedirectToRoute(new {controller = "Login", action = "Index"});
            if(!ModelState.IsValid) return RedirectToAction("Index", new {id = tarea.IdTablero});
            _tareaRepository.Create(tarea.IdTablero, new Tarea(tarea));
            return RedirectToAction("Index", new{id = tarea.IdTablero});
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return RedirectToAction("Error");
        }
    }

    [HttpGet]
    public IActionResult UpdateTarea(int id){
        try
        {
            if(!logueado()) return RedirectToRoute(new {controller = "Login", action = "Index"});
            var tarea = _tareaRepository.Get(id);
            if(tarea != null){
                var tablero = _tableroRepository.Get(tarea.IdTablero);
                if(tablero != null && (esAdmin() || tablero.IdUsuarioPropietario == Convert.ToInt32(HttpContext.Session.GetInt32("id")))){
                    return View(new ModificarTareaViewModel(tarea, _usuarioRepository.GetAll(), tablero.IdUsuarioPropietario));
                }
            }
            return RedirectToAction("Error");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return RedirectToAction("Error");
        }
    }
    [HttpPost]
    public IActionResult UpdateTarea(ModificarTareaViewModel tarea){
        try
        {
            if(!logueado()) return RedirectToRoute(new {controller = "Login", action = "Index"});
            if(!ModelState.IsValid) return RedirectToAction("Index", new {id = tarea.IdTablero});
            _tareaRepository.Update(tarea.Id,new Tarea(tarea));
            return RedirectToAction("Index", new{id = tarea.IdTablero});
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return RedirectToAction("Error");
        }
    }

    [HttpGet]
    public IActionResult UpdateEstado(int id){
        try
        {
            if(!logueado()) return RedirectToRoute(new {controller = "Login", action = "Index"});
            var tarea = _tareaRepository.Get(id);
            if(tarea != null && (esAdmin() || tarea.IdUsuarioAsignado == Convert.ToInt32(HttpContext.Session.GetInt32("id")) || _tareaRepository.GetIdOwner(id) == Convert.ToInt32(HttpContext.Session.GetInt32("id")))){
                return View(new ModificarEstadoTareaViewModel(tarea));
            }else{
                return RedirectToAction("Error");
            }
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return RedirectToAction("Error");
        }
    }
    [HttpPost]
    public IActionResult UpdateEstado(ModificarEstadoTareaViewModel tarea){
        try
        {
            if(!logueado()) return RedirectToRoute(new {controller = "Login", action = "Index"});
            if(!ModelState.IsValid) return RedirectToAction("Index", new {id = tarea.IdTablero});
            var tareaNueva = _tareaRepository.Get(tarea.Id);
            tareaNueva.Estado = tarea.Estado;
            _tareaRepository.Update(tarea.Id, tareaNueva);
            return RedirectToAction("Index", new{id = tarea.IdTablero});
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return RedirectToAction("Error");
        }
    }

    public IActionResult DeleteTarea(int id){
        try
        {
            if(!logueado()) return RedirectToRoute(new {controller = "Login", action = "Index"});
            if(!esAdmin() && _tareaRepository.GetIdOwner(id) != Convert.ToInt32(HttpContext.Session.GetInt32("id"))) return RedirectToAction("Error");
            if(!ModelState.IsValid) return RedirectToAction("Index", id);
            var idTablero = _tareaRepository.Get(id).IdTablero;
            _tareaRepository.Remove(id);
            return RedirectToAction("Index", new {id = idTablero});
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.ToString());
            return RedirectToAction("Error");
        }
    }

    public IActionResult Error(){
        return View(new ErrorViewModel());
    }

    private bool logueado(){
        return HttpContext.Session.Keys.Any();
    }

    private bool esAdmin(){
        return HttpContext.Session.Keys.Any() && HttpContext.Session.GetString("rol") == NivelAcceso.administrador.ToString();
    }
}

Views/Tablero/CreateTablero.cshtml
@{
    ViewData["Title"] = "Tableros";
}
@model tl2_tp10_2023_ezemrtz.ViewModels.CrearTableroViewModel

<section class="section_forms">
    <form asp-controller="Tablero" asp-action="CreateTablero" class="formsMVC form-v1">
        <legend>NUEVO TABLERO</legend>
        <div class="form-group mb-3">
            <label asp-for="@Model.Nombre"></label>
            <input asp-for="@Model.Nombre" class="form-control" />
            <span asp-validation-for="@Model.Nombre" class="text-danger"></span>    
        </div>
        <div class="form-group mb-3">
            <label asp-for="@Model.Descripcion"></label>
            <input asp-for="@Model.Descripcion" class="form-control" />
            <span asp-validation-for="@Model.Descripcion" class="text-danger"></span>    
        </div>
        <div class="form-group mb-3">
            <input asp-for="@Model.IdUsuarioPropietario" class="form-control" hidden />
        </div>
        <div class="form-group mb-3 btn-box">
            <button type="submit" class="btn btn-primary">Enviar</button>
        </div>
    </form>
</section>

@section Scripts{<partial name="_ValidationScriptsPartial"/>}

Views/Tablero/Index.cshtml
@{
    ViewData["Title"] = "Tableros";
}

@model tl2_tp10_2023_ezemrtz.ViewModels.ListarTablerosViewModel

<section class="tabIndexSection">
    <h3> Mis Tableros </h3>
    <a asp-controller="Tablero" asp-action="CreateTablero" class="btn btn-outline-dark margin" role="button">+ Nuevo Tablero</a>
</section>
<table class="table table-striped my-table">
    <thead>
        <th class="col1">Propietario</th>
        <th class="col2">Nombre</th>
        <th class="col3">Descripción</th>
        <th colspan="4" class="col4">Acciones</th>
    </thead>
    <tbody>
        @foreach(var tablero in Model.TablerosPropios){
            <tr>
                <td>@tablero.NombreUsuarioPropietario</td>
                <td>@tablero.Nombre</td>
                <td>@tablero.Descripcion</td>
                <td><a asp-controller="Tarea" asp-action="Index" asp-route-id="@tablero.IdTablero" class="btn btn-outline-info">Ver</a></td>
                @if(@tablero.IdUsuarioPropietario == Context.Session.GetInt32("id") || Context.Session.GetString("rol") == NivelAcceso.administrador.ToString()){
                    <td><a asp-controller="Tablero" asp-action="UpdateTablero" asp-route-id="@tablero.IdTablero" class="btn btn-outline-primary">Modificar</a></td>
                    <td><a asp-controller="Tablero" asp-action="DeleteTablero" asp-route-id="@tablero.IdTablero" class="btn btn-outline-danger" onclick="return confirm('¿Estas seguro que quieres eliminar el tablero? IMPORTANTE: Al hacerlo se eliminaran todas las tareas del mismo')">Eliminar</a></td>
                    <td><a asp-controller="Tarea" asp-action="CreateTarea" asp-route-id="@tablero.IdTablero" class="btn btn-outline-success">Agregar Tarea</a></td>
                }else{
                    <td></td>
                    <td></td>
                    <td></td>
                }
            </tr>
        }
    </tbody>
</table>
@if(Model.TablerosAjenos.Count != 0){
    <h3>Tableros con tareas asignadas</h3>
    <table class="table table-striped my-table">
        <thead>
            <th class="col1">Propietario</th>
            <th class="col2">Nombre</th>
            <th class="col3">Descripción</th>
            <th colspan="4" class="col4">Acciones</th>
        </thead>
        <tbody>
            @foreach(var tablero in Model.TablerosAjenos){
                <tr>
                    <td>@tablero.NombreUsuarioPropietario</td>
                    <td>@tablero.Nombre</td>
                    <td>@tablero.Descripcion</td>
                    <td><a asp-controller="Tarea" asp-action="Index" asp-route-id="@tablero.IdTablero" class="btn btn-outline-info">Ver</a></td>
                    @if(@tablero.IdUsuarioPropietario == Context.Session.GetInt32("id") || Context.Session.GetString("rol") == NivelAcceso.administrador.ToString()){
                        <td><a asp-controller="Tablero" asp-action="UpdateTablero" asp-route-id="@tablero.IdTablero" class="btn btn-outline-primary">Modificar</a></td>
                        <td><a asp-controller="Tablero" asp-action="DeleteTablero" asp-route-id="@tablero.IdTablero" class="btn btn-outline-danger" onclick="return confirm('¿Estas seguro que quieres eliminar el tablero? IMPORTANTE: Al hacerlo se eliminaran todas las tareas del mismo')">Eliminar</a></td>
                        <td><a asp-controller="Tarea" asp-action="CreateTarea" asp-route-id="@tablero.IdTablero" class="btn btn-outline-success">Agregar Tarea</a></td>
                    }else{
                        <td></td>
                        <td></td>
                        <td></td>
                    }
                </tr>
            }
        </tbody>
    </table>
}
@if(Context.Session.GetString("rol") == NivelAcceso.administrador.ToString() && Model.Tableros.Count != 0){
    <h3>Resto de tableros</h3>
    <table class="table table-striped my-table">
        <thead>
            <th class="col1">Propietario</th>
            <th class="col2">Nombre</th>
            <th class="col3">Descripción</th>
            <th colspan="4" class="col4">Acciones</th>
        </thead>
        <tbody>
            @foreach(var tablero in Model.Tableros){
                <tr>
                    <td>@tablero.NombreUsuarioPropietario</td>
                    <td>@tablero.Nombre</td>
                    <td>@tablero.Descripcion</td>
                    <td><a asp-controller="Tarea" asp-action="Index" asp-route-id="@tablero.IdTablero" class="btn btn-outline-info">Ver</a></td>
                    <td><a asp-controller="Tablero" asp-action="UpdateTablero" asp-route-id="@tablero.IdTablero" class="btn btn-outline-primary">Modificar</a></td>
                    <td><a asp-controller="Tablero" asp-action="DeleteTablero" asp-route-id="@tablero.IdTablero" class="btn btn-outline-danger" onclick="return confirm('¿Estas seguro que quieres eliminar el tablero? IMPORTANTE: Al hacerlo se eliminaran todas las tareas del mismo')">Eliminar</a></td>
                    <td><a asp-controller="Tarea" asp-action="CreateTarea" asp-route-id="@tablero.IdTablero" class="btn btn-outline-success">Agregar Tarea</a></td>
                    
                </tr>
            }
        </tbody>
    </table>
}

Views/Tablero/UpdateTablero.cshtml
@{
    ViewData["Title"] = "Tableros";
}
@model tl2_tp10_2023_ezemrtz.ViewModels.ModificarTableroViewModel

<section class="section_forms">
    <form asp-controller="Tablero" asp-action="UpdateTablero" class="formsMVC form-v1">
        <legend>MODIFICAR TABLERO</legend>
        <div class="form-group mb-3">
            <input asp-for="@Model.Id" hidden/>
            <label asp-for="@Model.Nombre"></label>
            <input asp-for="@Model.Nombre" class="form-control" />
            <span asp-validation-for="@Model.Nombre" class="text-danger"></span>    
        </div>
        <div class="form-group mb-3">
            <label asp-for="@Model.Descripcion"></label>
            <input asp-for="@Model.Descripcion" class="form-control" />
            <span asp-validation-for="@Model.Descripcion" class="text-danger"></span>    
        </div>
        <div class="form-group mb-3">
            <input asp-for="@Model.IdUsuarioPropietario" class="form-control" hidden/>
        </div>
        <div class="form-group mb-3 btn-box">
            <button type="submit" class="btn btn-primary">Enviar</button>
        </div>
    </form>
</section>

@section Scripts{<partial name="_ValidationScriptsPartial"/>}